#!/usr/bin/env bash
# Optional: install polylogue environment hooks / Redis bridge user service.
#
# Filesystem polylogue does NOT require a daemon — this script is for:
#   1. Shell hook: auto-export DEEPIRI_POLYLOGUE_ROOT when you cd into lydlr
#   2. Optional Redis PolyBridge user service (Linux/WSL/macOS launchd)
#
# Usage:
#   ./scripts/polylogue/install-service.sh hook          # recommended, all platforms
#   ./scripts/polylogue/install-service.sh redis-bridge # optional task dispatch daemon
#   ./scripts/polylogue/install-service.sh uninstall

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
POLY_ROOT="$REPO_ROOT/.deepiri/polylogue"
DEEPIRI_POLYLOGUE_REPO="${DEEPIRI_POLYLOGUE_REPO:-$HOME/Documents/Deepiri/deepiri-polylogue}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PLATFORM="$("$SCRIPT_DIR/detect-platform.sh")"

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/polylogue"
ENV_FILE="$CONFIG_DIR/lydlr.env"
HOOK_SNIPPET="$CONFIG_DIR/lydlr-cd-hook.sh"

install_hook() {
  mkdir -p "$CONFIG_DIR"
  cat >"$ENV_FILE" <<EOF
# Auto-generated by lydlr scripts/polylogue/install-service.sh
export DEEPIRI_POLYLOGUE_ROOT="$POLY_ROOT"
export DEEPIRI_POLYLOGUE_REPO="$DEEPIRI_POLYLOGUE_REPO"
export LYDLR_REPO_ROOT="$REPO_ROOT"
EOF

  cat >"$HOOK_SNIPPET" <<'EOF'
# lydlr polylogue — source from ~/.bashrc / ~/.zshrc:
#   [ -f ~/.config/polylogue/lydlr-cd-hook.sh ] && . ~/.config/polylogue/lydlr-cd-hook.sh

_lydlr_polylogue_cd_hook() {
  case "$PWD" in
    *"/lydlr"|*"/lydlr/"*|*"/lydlr")
      if [[ -f "${LYDLR_REPO_ROOT:-}/.deepiri/polylogue/meta.json" ]] || [[ -f "$PWD/.deepiri/polylogue/meta.json" ]]; then
        if [[ -d "$PWD/.deepiri/polylogue" ]]; then
          export DEEPIRI_POLYLOGUE_ROOT="$PWD/.deepiri/polylogue"
        fi
      fi
      ;;
  esac
}

if [[ -n "${ZSH_VERSION:-}" ]]; then
  autoload -U add-zsh-hook 2>/dev/null || true
  if typeset -f add-zsh-hook >/dev/null 2>&1; then
    add-zsh-hook chpwd _lydlr_polylogue_cd_hook
  fi
elif [[ -n "${BASH_VERSION:-}" ]]; then
  if [[ "${PROMPT_COMMAND:-}" != *"_lydlr_polylogue_cd_hook"* ]]; then
    PROMPT_COMMAND="_lydlr_polylogue_cd_hook${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
  fi
fi
EOF

  # Inject LYDLR_REPO_ROOT into hook (not heredoc quoted)
  sed -i "s|\${LYDLR_REPO_ROOT:-}|$REPO_ROOT|g" "$HOOK_SNIPPET" 2>/dev/null || \
    sed -i '' "s|\${LYDLR_REPO_ROOT:-}|$REPO_ROOT|g" "$HOOK_SNIPPET" 2>/dev/null || true

  echo "Wrote $ENV_FILE"
  echo "Wrote $HOOK_SNIPPET"
  echo ""
  echo "Add to ~/.bashrc or ~/.zshrc:"
  echo "  source $HOOK_SNIPPET"
  echo ""
  echo "Or one-shot before AI sessions:"
  echo "  source $ENV_FILE"

  case "$PLATFORM" in
    windows)
      echo ""
      echo "Windows (native): add to PowerShell profile:"
      echo "  \$env:DEEPIRI_POLYLOGUE_ROOT = '$POLY_ROOT'"
      ;;
    wsl)
      echo ""
      echo "WSL: hook works in bash/zsh inside WSL. Windows-side Cursor tabs should set"
      echo "DEEPIRI_POLYLOGUE_ROOT to the WSL path or use sync-pack output manually."
      ;;
  esac
}

install_redis_bridge_linux() {
  local unit_dir="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
  local unit_file="$unit_dir/polylogue-redis-bridge.service"
  mkdir -p "$unit_dir"

  cat >"$unit_file" <<EOF
[Unit]
Description=Deepiri Polylogue Redis bridge (optional)
After=network.target redis.service

[Service]
Type=simple
WorkingDirectory=$DEEPIRI_POLYLOGUE_REPO
Environment=DEEPIRI_POLYLOGUE_ROOT=$POLY_ROOT
ExecStart=$DEEPIRI_POLYLOGUE_REPO/.venv/bin/python3 -m polylogue start -c $DEEPIRI_POLYLOGUE_REPO/polylogue.yaml
Restart=on-failure
RestartSec=10

[Install]
WantedBy=default.target
EOF

  systemctl --user daemon-reload
  systemctl --user enable polylogue-redis-bridge.service
  systemctl --user start polylogue-redis-bridge.service || true
  echo "Installed user systemd unit: $unit_file"
  echo "Requires Redis on localhost:6379 and pip install -e '.[redis]' in deepiri-polylogue."
}

install_redis_bridge_macos() {
  local plist_dir="$HOME/Library/LaunchAgents"
  local plist="$plist_dir/com.deepiri.polylogue-redis.plist"
  mkdir -p "$plist_dir"

  cat >"$plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.deepiri.polylogue-redis</string>
  <key>ProgramArguments</key>
  <array>
    <string>$DEEPIRI_POLYLOGUE_REPO/.venv/bin/python3</string>
    <string>-m</string><string>polylogue</string>
    <string>start</string>
    <string>-c</string><string>$DEEPIRI_POLYLOGUE_REPO/polylogue.yaml</string>
  </array>
  <key>WorkingDirectory</key><string>$DEEPIRI_POLYLOGUE_REPO</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>DEEPIRI_POLYLOGUE_ROOT</key><string>$POLY_ROOT</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
</dict>
</plist>
EOF

  launchctl unload "$plist" 2>/dev/null || true
  launchctl load "$plist"
  echo "Installed launchd agent: $plist"
}

install_redis_bridge() {
  if [[ ! -d "$DEEPIRI_POLYLOGUE_REPO" ]]; then
    echo "Clone deepiri-polylogue to $DEEPIRI_POLYLOGUE_REPO first." >&2
    exit 1
  fi
  "$DEEPIRI_POLYLOGUE_REPO/.venv/bin/pip" install -e "$DEEPIRI_POLYLOGUE_REPO[redis]" -q 2>/dev/null || \
    "$DEEPIRI_POLYLOGUE_REPO/.venv/bin/pip" install -e "$DEEPIRI_POLYLOGUE_REPO" redis pyyaml -q

  case "$PLATFORM" in
    linux|wsl)
      if command -v systemctl >/dev/null 2>&1; then
        install_redis_bridge_linux
      else
        echo "systemctl not found; use: cd $DEEPIRI_POLYLOGUE_REPO && ./run_polylogue.sh start" >&2
        exit 1
      fi
      ;;
    macos)
      install_redis_bridge_macos
      ;;
    windows)
      echo "Windows native: run in background manually or use WSL redis-bridge install." >&2
      echo "  cd $DEEPIRI_POLYLOGUE_REPO && .venv/Scripts/python -m polylogue start" >&2
      exit 1
      ;;
    *)
      echo "Unknown platform; start bridge manually: ./run_polylogue.sh start" >&2
      exit 1
      ;;
  esac
}

uninstall_all() {
  rm -f "$ENV_FILE" "$HOOK_SNIPPET"
  systemctl --user disable polylogue-redis-bridge.service 2>/dev/null || true
  rm -f "${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user/polylogue-redis-bridge.service"
  systemctl --user daemon-reload 2>/dev/null || true
  launchctl unload "$HOME/Library/LaunchAgents/com.deepiri.polylogue-redis.plist" 2>/dev/null || true
  rm -f "$HOME/Library/LaunchAgents/com.deepiri.polylogue-redis.plist"
  echo "Removed polylogue hooks/service stubs."
}

case "${1:-hook}" in
  hook) install_hook ;;
  redis-bridge|redis) install_redis_bridge ;;
  uninstall) uninstall_all ;;
  *)
    echo "Usage: $0 {hook|redis-bridge|uninstall}" >&2
    echo "Platform detected: $PLATFORM" >&2
    exit 1
    ;;
esac
